---
name: On-PR to main

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write
  actions: read
  security-events: write

jobs:
  dependabot-auto-merge:
    uses: ./.github/workflows/99-dependabot-auto-merge.yml

  changeset-auto-merge:
    #uses: ./.github/workflows/99-changeset-auto-merge.yml
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
