---
name: Upload icons to GitHub

on:
  release:
    types: [published]

jobs:
  publish:
    name: Upload icons to GitHub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🆙 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 🆙 Setup pnpm config
        run: pnpm config set store-dir .pnpm-store

      - name: ⏬ Install pnpm
        run: pnpm install

      - name: ⏫ Upload Release Assets
        id: upload-release-asset
        uses: actions/github-script@v7
        env:
          ICON_RELEASE_ID: ${{ vars.ICON_RELEASE_ID }}
        with:
          result-encoding: json
          script: |
            const { default: release } = await import('${{ github.workspace }}/.github/scripts/release/index.js');
            const iconReleaseId = '${{ env.ICON_RELEASE_ID }}'
            const workspace = '${{ github.workspace }}';
            return await release({github, context, workspace, iconReleaseId})
